apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.masterService.name }}
spec:
  ports:
    - name: ntp
      port: 123
      targetPort: 123
      protocol: UDP
  selector:
    app: {{ .Values.masterDeployment.name }}
